// Initial menu data — seeded to Firebase on first setup
// Admin can modify all items from the Admin Portal

export const INITIAL_CATEGORIES = [
  { id: 'biryani-rice', name: 'Biryani & Rice', emoji: '🍚', order: 1, active: true },
  { id: 'curries-mains', name: 'Curries & Mains', emoji: '🍛', order: 2, active: true },
  { id: 'baked-pasta', name: 'Baked & Pasta', emoji: '🥘', order: 3, active: true },
  { id: 'wraps-rolls', name: 'Wraps, Rolls & Buns', emoji: '🌯', order: 4, active: true },
  { id: 'breads', name: 'Breads', emoji: '🫓', order: 5, active: true },
  { id: 'snacks-starters', name: 'Snacks & Starters', emoji: '🥟', order: 6, active: true },
  { id: 'sweets-desserts', name: 'Sweets & Desserts', emoji: '🍮', order: 7, active: true },
  { id: 'drinks', name: 'Drinks', emoji: '☕', order: 8, active: true },
];

export const INITIAL_MENU_ITEMS = [
  // Biryani & Rice
  {
    id: 'beef-biriyani',
    name: 'Beef Biriyani',
    description: 'Fragrant Long-Grain Rice with Tender Beef Chunks, Signature Blend of Biryani Spices',
    price: 75,
    discountPercent: 0,
    categoryId: 'biryani-rice',
    image: '',
    available: true,
  },
  {
    id: 'chicken-biriyani',
    name: 'Chicken Biriyani',
    description: 'Long-Grain Rice Cooked with Tender Chicken, Aromatic Biryani Spices, and a touch of Nuts',
    price: 65,
    discountPercent: 0,
    categoryId: 'biryani-rice',
    image: '',
    available: true,
  },
  {
    id: 'polau-rice',
    name: 'Polau Rice',
    description: 'Fragrant Basmati Rice Cooked with Ghee and Aromatic Spices',
    price: 25,
    discountPercent: 0,
    categoryId: 'biryani-rice',
    image: '',
    available: true,
  },
  // Curries & Mains
  {
    id: 'beef-curry',
    name: 'Beef Curry',
    description: 'Fresh Beef Chunks, Special House Blend of Masala, Onions Slow-Cooked to Perfection',
    price: 120,
    discountPercent: 0,
    categoryId: 'curries-mains',
    image: '',
    available: true,
  },
  {
    id: 'chicken-curry',
    name: 'Chicken Curry',
    description: 'Fresh Chicken Pieces, Onions & Garlic for a Rich Base, Special Blend of Aromatic Masala',
    price: 100,
    discountPercent: 0,
    categoryId: 'curries-mains',
    image: '',
    available: true,
  },
  {
    id: 'chicken-roast',
    name: 'Chicken Roast',
    description: 'Juicy Roasted Chicken, Special Masala and Garnished with Nuts',
    price: 70,
    discountPercent: 0,
    categoryId: 'curries-mains',
    image: '',
    available: true,
  },
  {
    id: 'chicken-chaap',
    name: 'Chicken Chaap',
    description: 'Tender Chicken Cooked in Rich Spiced Gravy with Special Chaap Masala',
    price: 70,
    discountPercent: 0,
    categoryId: 'curries-mains',
    image: '',
    available: true,
  },
  {
    id: 'grilled-chicken',
    name: 'Grilled Chicken',
    description: 'Garlic-Ginger Marinated Chicken with Special Grilled Masala',
    price: 70,
    discountPercent: 0,
    categoryId: 'curries-mains',
    image: '',
    available: true,
  },
  // Baked & Pasta
  {
    id: 'baked-chicken-patties',
    name: 'Baked Chicken Patties',
    description: 'Golden Baked Pastry Filled with Juicy Chicken, Onions, Creamy White Sauce',
    price: 35,
    discountPercent: 0,
    categoryId: 'baked-pasta',
    image: '',
    available: true,
  },
  {
    id: 'baked-chicken-pasta',
    name: 'Baked Chicken Pasta',
    description: 'Oven-Baked Pasta with Tender Chicken, Creamy White Sauce, Capsicum, and Cheese',
    price: 70,
    discountPercent: 0,
    categoryId: 'baked-pasta',
    image: '',
    available: true,
  },
  // Wraps, Rolls & Buns
  {
    id: 'chicken-wrap',
    name: 'Chicken Wrap',
    description: 'Grilled Chicken, Cucumber, Onion, Capsicum, and Special Pink Sauce',
    price: 40,
    discountPercent: 0,
    categoryId: 'wraps-rolls',
    image: '',
    available: true,
  },
  {
    id: 'cheesy-egg-paratha-roll',
    name: 'Cheesy Egg Paratha Roll',
    description: 'Fried Parata Wrapped with Egg Omelet and Melted Cheese',
    price: 30,
    discountPercent: 0,
    categoryId: 'wraps-rolls',
    image: '',
    available: true,
  },
  {
    id: 'cheesy-chicken-bun',
    name: 'Cheesy Chicken Bun',
    description: 'Soft Bun with Seasoned Chicken, Creamy White Sauce, Onions, Capsicum, and Melted Cheese',
    price: 40,
    discountPercent: 0,
    categoryId: 'wraps-rolls',
    image: '',
    available: true,
  },
  // Breads
  {
    id: 'garlic-butter-naan-roti',
    name: 'Garlic Butter Naan Roti',
    description: 'Soft Naan Roti Brushed with Garlic Butter, Warm and Flavorful',
    price: 20,
    discountPercent: 0,
    categoryId: 'breads',
    image: '',
    available: true,
  },
  // Snacks & Starters
  {
    id: 'singara',
    name: 'Singara',
    description: 'Flaky, Deep-Fried Pastries Stuffed with Chicken or English Potatoes, Onions, and Spiced with Mixed Masala',
    price: 10,
    discountPercent: 0,
    categoryId: 'snacks-starters',
    image: '',
    available: true,
  },
  {
    id: 'samocha',
    name: 'Samocha',
    description: 'Flaky, Deep-Fried Pastries Stuffed with Chicken, Onions, and Spiced with Mixed Masala',
    price: 10,
    discountPercent: 0,
    categoryId: 'snacks-starters',
    image: '',
    available: true,
  },
  {
    id: 'chicken-spring-roll',
    name: 'Chicken Spring Roll',
    description: 'Crispy Rolls Filled with Seasoned Chicken and Vegetables',
    price: 15,
    discountPercent: 0,
    categoryId: 'snacks-starters',
    image: '',
    available: true,
  },
  {
    id: 'chicken-noodles-pakora',
    name: 'Chicken Noodles Pakora',
    description: 'Crispy Deep-Fried Fritters Made with Chicken, Noodles, Capsicum, Onion, and Egg',
    price: 10,
    discountPercent: 0,
    categoryId: 'snacks-starters',
    image: '',
    available: true,
  },
  {
    id: 'peyaju',
    name: 'Peyaju',
    description: 'Crispy Lentil and Onion Fritters, Deep-Fried and Full of Flavor. (5 pieces)',
    price: 20,
    discountPercent: 0,
    categoryId: 'snacks-starters',
    image: '',
    available: true,
  },
  {
    id: 'beguni',
    name: 'Beguni',
    description: 'Crispy Battered Eggplant Fritters, Deep-Fried to Golden Perfection (5 pieces)',
    price: 20,
    discountPercent: 0,
    categoryId: 'snacks-starters',
    image: '',
    available: true,
  },
  // Sweets & Desserts
  {
    id: 'chhana-jilapi',
    name: 'Chhana Jilapi',
    description: 'Soft Chhana Spirals Fried and Soaked in Sweet Sugar Syrup. 1 box (10 pieces)',
    price: 110,
    discountPercent: 0,
    categoryId: 'sweets-desserts',
    image: '',
    available: true,
  },
  {
    id: 'jilapi',
    name: 'Jilapi',
    description: 'Traditional Golden Spiral Sweet, Crispy Outside and Soaked in Syrup (1 Kg)',
    price: 110,
    discountPercent: 0,
    categoryId: 'sweets-desserts',
    image: '',
    available: true,
  },
  {
    id: 'kaalo-jaam',
    name: 'Kaalo Jaam',
    description: 'Soft Fried Milk-based Balls Soaked in Syrup. 1 box (10 pieces)',
    price: 110,
    discountPercent: 0,
    categoryId: 'sweets-desserts',
    image: '',
    available: true,
  },
  {
    id: 'pera-sandesh',
    name: 'Pera Sandesh',
    description: 'Soft Chhana Milk Sweet with Sugar and Cardamom. 1 box (10-12 pieces)',
    price: 100,
    discountPercent: 0,
    categoryId: 'sweets-desserts',
    image: '',
    available: true,
  },
  // Drinks
  {
    id: 'brain-freeze-coffee',
    name: 'Brain-Freeze Coffee',
    description: 'A Chilling Cold Coffee So Icy, It\'ll Freeze Your Brain for a Few Seconds (1 Cup)',
    price: 25,
    discountPercent: 0,
    categoryId: 'drinks',
    image: '',
    available: true,
  },
];

// Default app settings
export const DEFAULT_SETTINGS = {
  storeName: 'QuikBites',
  storeTagline: 'South Asian Cloud Kitchen · Honiara',
  contactPhone: '7348123',
  currency: 'SBD',
  freeDeliveryThreshold: 100,
  defaultDeliveryFee: 10,
  deliveryAreas: [
    { id: 'honiara', name: 'Honiara', fee: 10 },
  ],
  openingHours: {
    open: '08:00',
    close: '21:00',
    isOpen: true,
    days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  },
  onlinePaymentDiscount: {
    enabled: false,
    type: 'percentage', // 'percentage' or 'fixed'
    value: 0,
  },
  mselenConfig: {
    enabled: false,
    merchantId: '',
    apiKey: '',
    apiUrl: '',
  },
};

// Helper: calculate discounted price
export function getDiscountedPrice(price, discountPercent) {
  if (!discountPercent || discountPercent <= 0) return price;
  return price - (price * discountPercent) / 100;
}
